### PR TITLE
support https:// sites by stripping with sslstrip

### PR DESCRIPTION
**Pull request by girst**
if this project wasn't perverse enough, the web-rendering-proxy now
requires another proxy as its dependency.

I've also worked on a simple GET-only form handler. interested?

### CODE REVIEW

**Comment by girst** [comment]
see #10

**Comment by tenox7** [comment]
Can you make it to a configurable option? eg SSLSTRIP=True|False

**Comment by girst** [comment]
@tenox7 -- like this?

**Comment by tenox7** [comment]
I have tried it a few times on a few environments and I get a lot of errors and issues. It works half the time. However it's still better than without it so I will merge it. Thank you!

**Pull request merged**
