### PR TITLE
Support for FreeBSD

### PR DESCRIPTION
**Pull request by miniupnp**

### CODE REVIEW

**Comment by tenox7** [comment]
Thank you! Does this actually work on FreeBSD?

**Comment by miniupnp** [comment]
Yes it works. I only had to install the Qt4Webkit python bindings
`sudo pkg install py27-qt4-webkit-4.12 `

**Comment by tenox7** [comment]
Thank you!! Could you also update readme with this?

**Comment by miniupnp** [comment]
see 5ec85e465252b8475a69b3eeafecffa3f7bd400c

**Pull request merged**
