### PR TITLE
add support for monochrome 2 colors

### PR DESCRIPTION
**Pull request by debounce2**
Add monochrome dithering when using 2 colors for better support on monochrome monitors

hn-mono

### CODE REVIEW

**Comment by tenox7** [comment]
Wow thank you! BTW doesn't this needs update to `go.mod` as well?

**Comment by tenox7** [comment]
Also have you tested use of halfgone with quantizer (github.com/ericpauley/go-quantize/quantize)? I'm thinking perhaps if halfgone is used then quantize doesn't have to be.

**Comment by debounce2** [comment]
I was using an old version of Go without modules. I added a commit to update the modules.

Without the quantizer, the image is a solid color.

**Comment by tenox7** [comment]
thank you!

**Review by tenox7 — APPROVED** [review]

**Pull request merged**
